version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 5000:5000
    env_file:
      - server/.env
    depends_on:
      - db
    command: npm start

  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - 3000:3000

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=petshopdb
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
