version: '3'
services:
  petshopdb:
    image: postgres:15.3
    restart: always
    container_name: petshopdb
    env_file:
      - server/.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 5000:5000
    env_file:
      - server/.env
    depends_on:
      - petshopdb
    command: npm start

  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - 3000:3000

volumes:
  postgres:
